### ISSUE TITLE
Pushed build directory, please remove

### ISSUE THREAD

**Issue by bellrise** [tlendev/linger#1]

**Comment by tlendev** [comment]
Build is here so people don't have to setup a ts compiler

**Comment by fenze** [comment]
Have you ever heard of the releases section in github bro?

**Comment by bellrise** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/toc.htm

**Comment by tlendev** [comment]
Releases will start to appear once i finish the build script. For now builds will be included in the repository

**Comment by bellrise** [comment]
🚀  Cool!
